### ISSUE TITLE
ds18b20 sensors with numeric ids crash the script

### ISSUE THREAD

**Issue by sarinkhan** [sarinkhan/rpi-sensor-fetcher#1]
if a ds18b20 has a fully numeric (no letters) in the id, the script ends throwing an exception : 
```
Traceback (most recent call last):
  File "./sensor-fetcher.py", line 194, in <module>
    main()
  File "./sensor-fetcher.py", line 187, in main
    insert_node_measures()
  File "./sensor-fetcher.py", line 168, in insert_node_measures
    value = ds18b20_temperature(sensor['probe_id'])
  File "./sensor-fetcher.py", line 51, in ds18b20_temperature
    sensor = W1ThermSensor(W1ThermSensor.THERM_SENSOR_DS18B20, probeid)
  File "/home/pi/.local/lib/python3.7/site-packages/w1thermsensor/core.py", line 174, in __init__
    self.BASE_DIRECTORY, self.slave_prefix + self.id, self.SLAVE_FILE
TypeError: can only concatenate str (not "int") to str

```

**Comment by sarinkhan** [comment]
fixed in commit ff0b409607df3eceb0149c0f200f61afcf8647a8
